# Generated by Django 5.2.2 on 2025-06-07 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(max_length=100)),
                ('expected_amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('received_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('txid', models.CharField(blank=True, max_length=128, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('sweep_txid', models.CharField(blank=True, max_length=128, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_transactions', to='merchants.merchant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_transactions', to='merchants.merchantuser')),
            ],
            options={
                'db_table': 'deposit_transactions',
            },
        ),
    ]
