# Generated by Django 5.2.2 on 2025-06-07 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposittransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_transactions', to='wallets.wallet'),
        ),
        migrations.AddIndex(
            model_name='deposittransaction',
            index=models.Index(fields=['merchant', 'status'], name='deposit_tra_merchan_85f523_idx'),
        ),
        migrations.AddIndex(
            model_name='deposittransaction',
            index=models.Index(fields=['transaction_number'], name='deposit_tra_transac_8af0d6_idx'),
        ),
        migrations.AddIndex(
            model_name='deposittransaction',
            index=models.Index(fields=['created_at'], name='deposit_tra_created_d5883d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deposittransaction',
            unique_together={('merchant', 'transaction_number')},
        ),
    ]
