# Generated by Django 5.2.2 on 2025-06-07 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mnemonic_encrypted', models.TextField()),
                ('hot_wallet_address', models.CharField(max_length=64, unique=True)),
                ('hot_wallet_private_key_encrypted', models.TextField()),
                ('deposit_min_amount', models.DecimalField(decimal_places=6, default=1, max_digits=20)),
                ('deposit_max_amount', models.DecimalField(decimal_places=6, default=10000, max_digits=20)),
                ('withdraw_min_amount', models.DecimalField(decimal_places=6, default=1, max_digits=20)),
                ('withdraw_max_amount', models.DecimalField(decimal_places=6, default=10000, max_digits=20)),
                ('callback_url', models.URLField(blank=True, null=True)),
                ('callback_secret', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'merchants',
                'indexes': [models.Index(fields=['is_active'], name='merchants_is_acti_f2e8f9_idx'), models.Index(fields=['created_at'], name='merchants_created_f43d1d_idx')],
            },
        ),
        migrations.CreateModel(
            name='MerchantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(max_length=64)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='merchants.merchant')),
            ],
            options={
                'db_table': 'merchant_users',
                'indexes': [models.Index(fields=['merchant'], name='merchant_us_merchan_64e4a6_idx'), models.Index(fields=['user_uid'], name='merchant_us_user_ui_36c3da_idx')],
                'unique_together': {('merchant', 'user_uid')},
            },
        ),
    ]
