# Generated by Django 5.2.2 on 2025-06-07 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=64, unique=True)),
                ('private_key_encrypted', models.TextField()),
                ('derivation_index', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('hot', 'Hot Wallet'), ('sub', 'Sub-wallet'), ('cold', 'Cold Wallet')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sweep_at', models.DateTimeField(blank=True, null=True)),
                ('last_usdt_balance', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('last_trx_balance', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('last_balance_checked_at', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='merchants.merchant')),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('consolidation', 'Consolidation'), ('gas', 'Gas/Fee')], max_length=20)),
                ('txid', models.CharField(blank=True, max_length=128, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('gas_used', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.deposittransaction')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='merchants.merchant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='merchants.merchantuser')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to='wallets.wallet')),
            ],
            options={
                'db_table': 'wallet_transactions',
            },
        ),
    ]
